# Generated by Django 5.0.4 on 2024-04-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affairs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=255, verbose_name='Дата решения')),
                ('plaintiff', models.CharField(max_length=255, verbose_name='Истец')),
                ('defendant', models.CharField(max_length=255, verbose_name='Ответчик')),
                ('court', models.CharField(max_length=255, verbose_name='Суд')),
                ('dispute', models.CharField(max_length=255, verbose_name='Суть спора')),
                ('summ_plaintiff', models.CharField(max_length=255, verbose_name='Сумма иска')),
                ('result_client', models.CharField(max_length=255, verbose_name='Сумму отбили/Снизили')),
                ('result_court', models.TextField(max_length=1000, verbose_name='Результат')),
                ('image_result', models.ImageField(blank=True, null=True, upload_to='photo', verbose_name='Фото')),
                ('purist', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ответственный юрист')),
                ('urls', models.CharField(max_length=300, verbose_name='Адрес на дело')),
            ],
            options={
                'verbose_name': 'Мои дела',
                'verbose_name_plural': 'Мои дела',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('numbers_phone', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('dispute', models.CharField(max_length=255, verbose_name='Суть дела')),
                ('username', models.CharField(max_length=255, verbose_name='ТГ')),
            ],
            options={
                'verbose_name': 'Записи на консультацию',
                'verbose_name_plural': 'Записи на консультацию',
            },
        ),
    ]
