# Generated by Django 5.0.4 on 2024-04-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myurist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='affairs',
            name='category',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='affairs',
            name='role',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Моя роль'),
        ),
        migrations.AddField(
            model_name='affairs',
            name='sub_category',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='affairs',
            name='court',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Суд'),
        ),
        migrations.AlterField(
            model_name='affairs',
            name='date',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата решения'),
        ),
        migrations.AlterField(
            model_name='affairs',
            name='defendant',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ответчик'),
        ),
        migrations.AlterField(
            model_name='affairs',
            name='dispute',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Суть спора'),
        ),
        migrations.AlterField(
            model_name='affairs',
            name='plaintiff',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Истец'),
        ),
        migrations.AlterField(
            model_name='affairs',
            name='result_client',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Сумму отбили/Снизили'),
        ),
        migrations.AlterField(
            model_name='affairs',
            name='result_court',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Результат'),
        ),
        migrations.AlterField(
            model_name='affairs',
            name='summ_plaintiff',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Сумма иска'),
        ),
        migrations.AlterField(
            model_name='affairs',
            name='urls',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Адрес на дело'),
        ),
        migrations.AlterField(
            model_name='record',
            name='dispute',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Суть дела'),
        ),
        migrations.AlterField(
            model_name='record',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='record',
            name='numbers_phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='record',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ТГ'),
        ),
    ]
